### ISSUE TITLE
Better organize the output files

### ISSUE THREAD

**Issue by matthuska** [rki-mf1/2023-Workshop-MISSIoN-Nanopore#16]
Currently the output directory looks like this when all hands-on and solutions commands are finished running:

```
 2023-08-nanopore-workshop-example-bacteria
 2023-08-nanopore-workshop-example-bacteria.zip
 bacteria
 bacteria-filtered.fastq
 eco-consensus-mapping.sam
 eco-consensus-racon.fasta
 eco-consensus-racon.fasta.fai
 eco-consensus-racon.fasta.map-ont.mmi
 eco-fastqc
 eco-filtered.fastq
 ecoli-annotation.gff
 ecoli-reference.fna
 eco-mapping-ref.sam
 eco-mapping-ref.sorted.bam
 eco-mapping-ref.sorted.bam.bai
 eco-mapping.sam
 eco-mapping.sorted.bam
 eco-mapping.sorted.bam.bai
 eco-medaka
 envs
 flye_output
 flye-output-bacteria
 flye-output-sal1
 hands-on.sh
 ideel
 input-data
 nanoplot
 sal1-filtered.fastq
```

This is a bit of a mess. It would be nice to properly organize the data into e.g. separate folders per pathogen, with clear naming of the output files depending on what tools were used to generate them (this last part is already not too bad).

**Comment by hoelzer** [comment]
Transferred to https://github.com/rki-mf1/workshop-nanopore-bioinformatics/issues/7
