### ISSUE TITLE
Create an .md file with solutions to the Exercise and Bonus hands-on work

### ISSUE THREAD

**Issue by matthuska** [rki-mf1/2023-Workshop-MISSIoN-Nanopore#8]
I would suggest adding a new .md file for each day called `solutions.md`, which give solutions to the Exercise and Bonus. This would let us test that part of the workshop and give students someplace to look if they get super stuck on that part of the hands-on after the workshop is over. The `test.sh` script would need to be updated to include the code from these new files.

**Comment by matthuska** [comment]
Work on this has started in #12 . Still need to finish that but it gives the basic framework and sections that need to be completed. Also it is already incorporated into the semi-automatic testing script.

**Comment by hoelzer** [comment]
Transfered to https://github.com/rki-mf1/workshop-nanopore-bioinformatics/issues/3
